config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home', id: 'home'

  get 'index.html', to: redirect('/')
  get '/home', to: redirect('/')
  get '/about' => 'pages#about'

  get '/directory' => 'admin/cohorts#index'

  resources :maps, only: [:index]

  resources :fellows, only: [:index, :new, :edit, :show]

  get 'profile' => 'fellows#show'

  namespace :admin do
    root to: 'cohorts#index'
    resources :cohorts
    resources :fellows
    resources :locales
  end

end

app/models/cohort.rb
class Cohort < ActiveRecord::Base

  validates :name, presence: true
  validates :year, uniqueness: true, presence: true, length: { maximum: 4 }, numericality: { only_integer: true }

  has_many :fellows

  before_destroy :check_destroyability


  CLASS_YEARS =  ['2011', '2012', '2013', '2014', '2015', '2016']

  def check_destroyability
    if fellows.present?
      errors.add :base, "Can't be deleted because it has Fellows attached to this class"
      return false
    end
    true
  end

end

app/controllers/admin/cohorts_controller.rb
class Admin::CohortsController < ApplicationController

  include SortedColumns

  before_action :load_cohort, only: [:show, :edit, :update, :destroy]
  before_action :prep_form, only: [:new, :edit]

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.save
      redirect_to admin_cohorts_path, notice: "#{@cohort.name} was successfully created"
    else
      prep_form
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @cohort.update_attributes(cohort_params)
      redirect_to admin_cohorts_path
    else
      prep_form
      render :edit
    end
  end

  def index
    @cohorts = Cohort.order(sort_column + " " + sort_direction)
  end

  def destroy
    if @cohort.destroy
      redirect_to admin_cohorts_path, notice: "#{@cohort.name} was deleted"
    else
      redirect_to admin_cohorts_path, alert: "Delete failed: #{@cohort.errors.full_messages.first}"
    end
  end

  protected

  def cohort_params
    params.require(:cohort).permit(
      :name,
      :year
    )
  end

  def load_cohort
    @cohort = Cohort.find(params[:id])
  end

  def prep_form
    @cohorts = Cohort.all
  end

  def sort_column
    Cohort.column_names.include?(params[:sort]) ? params[:sort] : "year"
  end


end

app/helpers/admin/cohorts_helper.rb
module Admin::CohortsHelper
end

app/views/admin/cohorts/_fellow_list.html.erb
<div class="container">
  <div class="title">Fellows</div>
  <div class="table is-striped">
    <table>
      <tr>
        <th><%= sortable "first_name", "First Name" %>
        </th>
        <th><%= sortable "last_name", "Last Name" %>
        </th>
      </tr>
      <% @cohort.fellows.each do | fellow | %>
        <tr>
          <td><%= fellow.first_name %></td>
          <td><%= fellow.last_name %></td>
          <td>
            <%= link_to "Details", admin_cohort_fellow_path(fellow.cohort, fellow), :class => "button" %>
          </td>
          <td>
            <%= link_to "Edit", edit_admin_cohort_fellow_path(fellow.cohort, fellow), :class => "button" %>
            <%#= link_to "Edit", [:admin, :edit, @cohort, fellow], :class => "button" %>
          </td>
          <td>
            <%#= link_to "Delete", admin_cohort_fellow_path(fellow.cohort, fellow), method: :delete, data: { confirm: "Are you sure you want to delete this Fellow?" }, :class => "button" %>
            <%= link_to "Delete", [:admin, @cohort, fellow], method: :delete, data: { confirm: "Are you sure you want to delete this Fellow?" }, :class => "button" %>
          </td>
        </tr>
      <% end %>
    </table>

  <div class="section">
    <div class="container">
      <%= link_to "Add Fellow to this Class", new_admin_cohort_fellow_path(@cohort), :class => "button is-success" %>
    </div>
  </div>

  </div>
</div>

app/views/admin/cohorts/_form.html.erb
<%= render 'shared/error_messages', object: @cohort if @cohort.errors.any? %>
<div class="section">
  <div class="container">
    <label class="label"><strong>Name</strong></label>
    <p class="control">
      <%= form.text_field :name, placeholder: "Class of 2016" %>
    </p>
    <label class="label"><strong>Year</strong></label>
    <p class="control">
      <%= form.text_field :year, placeholder: "2016" %>
    </p>
  </div>
</div>

<div class="section">
  <div class="container">
    <p class="control">
      <%= form.submit "Submit", :class => "button is-info" %>
    </p>
  </div>
</div>

app/views/admin/cohorts/edit.html.erb
<% title "Admin - Edit A Class" %>

<div class="section">
  <div class="container">
    <div class="title">Edit: <%= @cohort.name %> Program #<%= @cohort.id %></div>
    <div class="container">
      <%= form_for [:admin, @cohort] do |f| %>
        <%= render f %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/cohorts/index.html.erb
<% title "Classes" %>

<div class="section">
  <div class="container">
    <div class="title">Classes</div>
    <div class="table is-striped">
      <table>
        <tr>
          <th><%= sortable "name", "Program Name" %>
            <span class="icon is-small"><i class="fa fa-sort-desc"></i></span>
          </th>
          <th><%= sortable "year", "Year" %>
            <span class="icon is-small"><i class="fa fa-sort-desc"></i></span>
          </th>
          <th>Fellows</th>
        </tr>
        <% @cohorts.each do |cohort| %>
          <tr>
            <td><%= link_to cohort.name, admin_cohort_path(cohort.id)%></td>
            <td><%= cohort.year %></td>
            <td>
              <%= "#{cohort.fellows.count} Fellows" %>
            </td>
          </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="section">
  <div class="container">
      <%= link_to "Add A New Class", new_admin_cohort_path, :class => 'button is-success' %>
  </div>
</div>

app/views/admin/cohorts/new.html.erb
<% title "Admin - Add A New Class" %>

<div class="section">
  <div class="container">
    <div class="title">Add a Class</div>
    <%= form_for [:admin, @cohort] do |f| %>
      <%= render f %>
    <% end %>
  </div>
</div>

app/views/admin/cohorts/show.html.erb
<% title "Cansbridge - #{@cohort.name}" %>

<div class="section">
  <div class="container">
    <div class="title"><%= @cohort.name %></div>

    <table class="table">
      <tr>
        <td>Name</td><td><%= @cohort.try :name %></td>
      </tr>
      <tr>
        <td>Year</td><td><%= @cohort.try :year %></td>
      </tr>
      <tr>
        <td>Fellows</td><td><%= @cohort.fellows.count %></td>
      </tr>
      <tr>
        <td>Updated on</td><td><%= @cohort.updated_at.strftime("%B %e, %Y") %></td>
      </tr>
    </table>
  </div>
</div>

<div class="section">
  <div class="container">
    <%= link_to "Back To Classes", admin_cohorts_path, :class => "button" %>
    <%= link_to "Edit", edit_admin_cohort_path(@cohort.id), :class => "button is-warning" %>
    <%= link_to "Delete", admin_cohort_path(@cohort.id), method: :delete, data: {confirm: "Are you sure you want to delete this Class?"}, :class => "button is-danger" %>
  </div>
</div>

<% if false %>
<div class="section">
  <div class="container">
    <%= render 'fellow_list' %>
  </div>
</div>
<% end %>