config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home', id: 'home'

  get 'index.html', to: redirect('/')
  get '/home', to: redirect('/')
  get '/about' => 'pages#about'

  get '/directory' => 'admin/cohorts#index'

  resources :maps, only: [:index]

  resources :fellows, only: [:index, :new, :edit, :show]

  get 'profile' => 'fellows#show'

  namespace :admin do
    root to: 'cohorts#index'
    resources :cohorts
    resources :fellows
    resources :locales
  end

end

app/models/fellow.rb
class Fellow < ActiveRecord::Base

  belongs_to :cohort
  has_many :locales

  # accepts_nested_attributes_for :locales, allow_destroy: true, reject_if: :all_blank

  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 20 }
  # validates :year, presence: true, length: { maximum: 4 }


  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/admin/fellows_controller.rb
class Admin::FellowsController < ApplicationController

  include SortedColumns

  before_action :require_fellow, only: [:edit, :update, :show, :destroy]
  before_action :prep_form

  # scope :for_cohort,  -> (cohort) { where(cohort_id: cohort) }

  def new
    @fellow = Fellows.new
  end

  def create
    @fellow = Fellow.new(fellow_params)
    if @fellow.save
      redirect_to admin_fellows_path, notice: "#{@fellow.full_name} was successfully created"
    else
      prep_form
      render :new
    end
  end

  def index
    @fellows = Fellow.all
    @fellows = Fellow.order(sort_column + " " + sort_direction)
  end

  def show
  end

  def edit
  end

  def update
    if @fellow.update_attributes(fellow_params)
      redirect_to admin_fellows_path
      return
    else
      prep_form
      render :edit
    end
  end

  def destroy
    if @fellow.destroy
      redirect_to admin_fellows_path, notice: "#{@fellow.full_name} was deleted"
    else
      redirect_to admin_fellows_path, alert: "#{@fellow.full_name} can't be deleted because there are applications"
    end
  end
  #
  # def add_locale
  #   @fellow = @cohort.fellows.find(params[:id])
  #   @fellow.locales.build
  #   render :edit
  # end


  protected

  def fellow_params
    params.require(:fellow).permit(
      :first_name,
      :last_name,
      :email,
      :cohort_id,
      locales_attributes: [:id, :city, :country, :period, :_destroy]
    )
  end

  def require_fellow
    @fellow = Fellow.find(params[:id])
  end

  def prep_form
    @cohorts = Cohort.all
  end

  def sort_column
    Fellow.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  end

end

app/controllers/fellows_controller.rb
class FellowsController < ApplicationController

  def index
    # @fellows = Fellow.all.order(cansbridge_year: :desc)
    # @geojson = Array.new
    # build_geojson(fellow, @geojson)
  end

  def show
     @fellow = Fellow.find(params[:id])

  end

  # @fellow.each do |fellow|
  #   @geojson << {
  #     type: 'Feature',
  #     geometry: {
  #       type: 'Point',
  #       coordinates: [fellow.longitude, fellow.latitude]
  #     },
  #     properties: {
  #       name: fellow.name,
  #       address: fellow.street,
  #       :'marker-color' => '#00607d',
  #       :'marker-symbol' => 'circle',
  #       :'marker-size' => 'medium'
  #     }
  #   }
  # end

  # respond_to do |format|
  #   format.html
  #   format.json { render json: @geojson }  #responds with the created JSON object
  # end

  # def build_geojson(fellows, geojson)
  #   fellows.each do |fellow|
  #     geojson << GeojsonBuilder.build_event(fellow)
  #   end
  # end

end

app/helpers/admin/fellows_helper.rb
module Admin::FellowsHelper
end

app/views/admin/fellows/_fellow_list.html.erb
<div class="container">
  <div class="title">Fellows</div>
  <div class="table is-striped">
    <table>
      <tr>
        <th><%= sortable "first_name", "First Name" %>
        </th>
        <th><%= sortable "last_name", "Last Name" %>
        </th>
      </tr>
      <% @fellows.each do | fellow | %>
        <tr>
          <td><%= fellow.first_name %></td>
          <td><%= fellow.last_name %></td>
          <td>
            <%= link_to "Details", admin_fellow_path(fellow.cohort, fellow), :class => "button" %>
          </td>
          <td>
            <%= link_to "Edit", edit_admin_fellow_path(fellow.cohort, fellow), :class => "button" %>
            <%#= link_to "Edit", [:admin, :edit, @cohort, fellow], :class => "button" %>
          </td>
          <td>
            <%#= link_to "Delete", admin_cohort_fellow_path(fellow.cohort, fellow), method: :delete, data: { confirm: "Are you sure you want to delete this Fellow?" }, :class => "button" %>
            <%= link_to "Delete", [:admin, @cohort, fellow], method: :delete, data: { confirm: "Are you sure you want to delete this Fellow?" }, :class => "button" %>
          </td>
        </tr>
      <% end %>
    </table>

  <div class="section">
    <div class="container">
      <%= link_to "Add Fellow to this Class", new_admin_fellow_path, :class => "button is-success" %>
    </div>
  </div>

  </div>
</div>

app/views/admin/fellows/_form.html.erb
<% f = form %>

<%= render 'shared/error_messages', object: f.object %>
<div class="section">
  <div class="container">
    <label class="label">First Name</label>
    <p class="control">
      <%= form.text_field :first_name, placeholder: "Ross" %>
    </p>
    <label class="label">Last Name</label>
    <p class="control">
      <%= form.text_field :last_name, placeholder: "Kelly" %>
    </p>
    <label class="label">Email</label>
    <p>To recieve Cansbridge updates, newsletters, and events</p>
    <p class="control">
      <%= form.text_field :email, placeholder: "ross@boss.ca" %>
    </p>
    <label class="label">Email</label>
    <p>Other email (secondary, company email)</p>
    <p class="control">
      <%= form.text_field :email, placeholder: "ross@company.ca" %>
    </p>
  </div>
</div>

  <p class="control">
    <%= form.submit "Submit", :class => "button is-info" %>
  </p>


  <% if false %>
    <div class="row">
      <% if @project_member.image? %>
        <div class="large-12 columns">
          <%= image_tag @almuni.image_url, data: { 'no-retina' => ''}  %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/admin/fellows/edit.html.erb
<% title "Edit: #{@fellow.full_name}" %>

<div class="section">
  <div class="container">
    <div class="title">Edit: <%= @fellow.full_name %> </div>
      <h2 class="subtitle"><%= @fellow.cohort.name %></h2>
  </div>

  <div class="container">
  <%= form_for @fellow,:url => admin_fellow_path(@fellow), :html => { :multipart => true } do |f| -%>
    <%= render f %>
  <% end %>
  </div>
</div>

app/views/admin/fellows/index.html.erb
<div class="container">
  <div class="title">Fellows</div>
  <div class="table is-striped">
    <table>
      <tr>
        <th><%= sortable "first_name", "First Name" %>
        </th>
        <th><%= sortable "last_name", "Last Name" %>
        </th>
      </tr>
      <% @fellows.each do |fellow| %>
        <tr>
          <td><%= fellow.first_name %></td>
          <td><%= fellow.last_name %></td>
          <td>
            <%= link_to "Details", admin_fellow_path(fellow.cohort, fellow), :class => "button" %>
          </td>
          <td>
            <%= link_to "Edit", edit_admin_fellow_path(fellow.cohort, fellow), :class => "button" %>
            <%#= link_to "Edit", [:admin, :edit, @cohort, fellow], :class => "button" %>
          </td>
          <td>
            <%#= link_to "Delete", admin_cohort_fellow_path(fellow.cohort, fellow), method: :delete, data: { confirm: "Are you sure you want to delete this Fellow?" }, :class => "button" %>
            <%= link_to "Delete", [:admin, @cohort, fellow], method: :delete, data: { confirm: "Are you sure you want to delete this Fellow?" }, :class => "button" %>
          </td>
        </tr>
      <% end %>
    </table>

  <div class="section">
    <div class="container">
      <%= link_to "Add Fellow to this Class", new_admin_fellow_path, :class => "button is-success" %>
    </div>
  </div>

  </div>
</div>

app/views/admin/fellows/new.html.erb
<% title "Admin - New Fellow" %>

<div class="section">
  <div class="container">
    <div class="title"><%= @cohort.name %>: New Member</div>
  </div>

  <div class="container">
    <%= form_for [:admin, @fellow],:url => admin_fellows_path(@fellow), :html => { :multipart => true } do |f| -%>
      <%= render f %>

    <% end %>
  </div>
</div>

app/views/admin/fellows/show.html.erb
<% title "Admin - #{@fellow.full_name}" %>

<div class="section">
  <div class="container">
    <div class="title"><%= @fellow.full_name %></div>
    <table class="table">
      <tr>
        <td>First Name</td><td><%= @fellow.first_name %></td>
      </tr>
      <tr>
        <td>Last Name</td><td><%= @fellow.last_name %></td>
      </tr>
      <tr>
        <td>Class</td><td><%= @fellow.cohort.year %></td>
      </tr>
      <tr>
        <td>Updated at</td><td><%= @fellow.updated_at.strftime("%B %e, %Y") %></td>
      </tr>
    </table>
  </div>
    <div class="container">
      <%= link_to "Edit", edit_admin_fellow_path(@fellow.cohort, @fellow.id), class: "button" %>
    </div>
</div>

<div class="section">
  <div class="container">
    <div class="subtitle">Locations</div>
      <%= render :file => 'admin/locales/show', locale: locale %>
  </div>
</div>